<?php get_header() ?>

<main id="main" class="site-main" role="main">
	<article id="post-<?php the_ID(); ?>" class="card">
	
		<?php while ( have_posts() ) : the_post();?>
		<div class="post-container">
		    <header class="post-header">
				<h2 class="post-title"><?php echo the_title(); ?><h2>
			</header>
			<div class="post-content">
				<?php  echo the_content();?>
			</div>
		</div>



		<footer class="post-footer">
			<h3>partial</h3>
			<p>generated by: single.php using to display single post content</p>
			<p>template location: <span class="attention">single.php</span></p>
		</footer>

	</article>
	<?php endwhile; ?>
	
</main>

<?php get_footer(); ?>